### PR TITLE
Revert "Core: Ignore readonly as well as disabled fields."

### PR DESCRIPTION
**Pull request by jamespratt**
This reverts commit 9f4ba10ea79b4cf59225468d6ec29911f0e53a0a.  Refer to issue #1300.

### CODE REVIEW

**Comment by jzaefferer** [comment]
Thanks! Could you look into a PR for the [documentation](https://github.com/jzaefferer/validation-content) as well?

**Comment by jamespratt** [comment]
Thank you, Jörn.  I'm working on the documentation and would like to extend it to better document all of the default settings.

**Comment by jzaefferer** [comment]
Great, thank you.

**Comment by kleen** [comment]
readonly="readonly"  验证不了, 难道只能修改源码?      $.validator.setDefaults(':hidden');  也不行

**Pull request closed without merging**
