### PR TITLE
Update step validation to handle floating points correctly

### PR DESCRIPTION
**Pull request by tbjers**
This is a new PR based on #1760. I couldn't find a way to modify that actual PR with my additional changes so I created a new PR that includes unit tests. @adhayward @staabm 

Tests: Added regression unit tests for PR #1760
Testing small fraction steps to ensure correct modulo operation.
Cleaned up @adhayward's formatting, was using spaces instead of tabs.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder_()
See: http://wiki.ecmascript.org/doku.php?id=strawman:modulo_operator
See: http://stackoverflow.com/questions/3966484/floating-point-numbers-and-javascript-modulus-operator

### CODE REVIEW

**Comment by staabm** [comment]
@DrowningElysium can you confirm this PR fixes your issue?

**Comment by tbjers** [comment]
@staabm Marked thumbs up. @adhayward's code is in this patch, I cloned their branch and just cleaned up the whitespace and added the necessary unit tests.

**Comment by staabm** [comment]
will this PR break BC for numbers in which the `.` char is used as a thousands separator?

**Comment by tbjers** [comment]
I'll write some tests for those types of numbers as well.

**Comment by tbjers** [comment]
@staabm This PR will break BC for input that uses the `.` char as a thousand separator. This, however, is also true for the `range` method. Should we then support these out of the box programmatically, or should we maybe add an option for specifying thousand separator when instantiating the validate object?

**Comment by staabm** [comment]
rebased, squashed and merged manually in  fbfccba

**Comment by JayAchTee** [comment]
This solution does not work for me using a values 0.30, 0.60 and 0.70 and a step of 0.10.

**Comment by JayAchTee** [comment]
The only solution that I am satisfied with thus far is to multiply "value" and `"param"` by 10 until param is a natural number and then do the modulo as in
```
			while (Math.floor(param) != param)
			{
				param *= 10;
				value *= 10;
			}

```

**Comment by staabm** [comment]
@JayAchTee could you open a new issue with a fiddle which reproduces the issue?

**Comment by mikes-gh** [comment]
@tbjers @staabm Thanks for this.
Now I can validate currency with step 0.01.
Any chance of making 1.15.1 official as this seems like quite an important fix.
I see most of the CDNs have links for 1.15.1 already.
But my bower package manager is only showing 1.15.0 and https://jqueryvalidation.org/ is still showing 1.15.0 as the released version.
Might save others some time as it took me a while to work out that I needed to get the unofficial package.

**Comment by Arkni** [comment]
> But my bower package manager is only showing 1.15.0

Just tried installing the package and I get the latest version `1.15.1`
```bash
arkni: tmp $ bower install jquery-validation
bower cached        https://github.com/jzaefferer/jquery-validation.git#1.15.1
bower validate      1.15.1 against https://github.com/jzaefferer/jquery-validation.git#*
bower cached        https://github.com/jquery/jquery-dist.git#3.1.0
bower validate      3.1.0 against https://github.com/jquery/jquery-dist.git#>= 1.7.2
bower new           version for https://github.com/jquery/jquery-dist.git#>= 1.7.2
bower resolve       https://github.com/jquery/jquery-dist.git#>= 1.7.2
bower checkout      jquery#3.1.1
bower progress      jquery#>= 1.7.2 Receiving objects:  21% (30/142)
bower progress      jquery#>= 1.7.2 Receiving objects:  22% (32/142), 76.00 KiB | 66.00 KiB/s
bower progress      jquery#>= 1.7.2 Receiving objects:  23% (33/142), 76.00 KiB | 66.00 KiB/s
bower progress      jquery#>= 1.7.2 Receiving objects:  25% (36/142), 148.00 KiB | 62.00 KiB/s
bower progress      jquery#>= 1.7.2 Receiving objects:  26% (38/142), 220.00 KiB | 62.00 KiB/s
bower progress      jquery#>= 1.7.2 Receiving objects:  35% (50/142), 260.00 KiB | 60.00 KiB/s
bower progress      jquery#>= 1.7.2 Receiving objects:  36% (52/142), 260.00 KiB | 60.00 KiB/s
bower progress      jquery#>= 1.7.2 Receiving objects:  37% (53/142), 260.00 KiB | 60.00 KiB/s
bower progress      jquery#>= 1.7.2 Receiving objects:  38% (54/142), 260.00 KiB | 60.00 KiB/s
bower resolved      https://github.com/jquery/jquery-dist.git#3.1.1
bower install       jquery-validation#1.15.1
bower install       jquery#3.1.1

jquery-validation#1.15.1 bower_components/jquery-validation
└── jquery#3.1.1

jquery#3.1.1 bower_components/jquery
```

> https://jqueryvalidation.org/ is still showing 1.15.0 as the released version.

I think it's a cache problem. The server sometimes serves the old version  of the home page and sometimes the new one.

**Comment by mikes-gh** [comment]
OK `bower install jquery-validation` works for me as well.
Looks like its an issue with the Visual Studio 2015 Bower package manger only showing 1.15.0
Cant get the home page to display 1.15.1 though even using a third party request outside my network.

**Pull request closed without merging**
