### PR TITLE
Added support for custom email patterns, provided via options.emailRegex.

### PR DESCRIPTION
**Pull request by staabm**
Uses the current email regex per default to keep BC.

### CODE REVIEW

**Comment by jzaefferer** [comment]
I'm okay with making the email validation configurable, but I really want to avoid adding more options. Partly because there are too many already, partly because this would tie in the method even more into the core.

To take a step back, why do you need this as an option? Could you override the email method as needed? Or use a custom email method when you need to the default on the same page?

**Comment by staabm** [comment]
> To take a step back, why do you need this as an option? Could you override the email method as needed? Or use a custom email method when you need to the default on the same page?

I could of course use a separate email validation method. IMO email validation will only be different in the email format and per definition will not have other differences, so I decided to go this road.

Per se, I would love to reduce the jquery-validation core to less lines and have a built which only contains the rules I really need for a certain app.

**Comment by staabm** [comment]
As you already know, email pattern issues are the most reported errors in this tracker, therefore solving the issue using a config param is a must have for a lot of our users. (I am not saying it has to be a option passed to the validator)

**Comment by staabm** [comment]
@jzaefferer what do you think, how to proceed?

**Comment by staabm** [comment]
I just tried the other way you proposed.

In case we promote the `$.validator.methods.<myRule>` properties to be part of the public api, I could override the native-email method with my custom regex without providing another option.

@jzaefferer wdyt?

**Comment by jzaefferer** [comment]
That looks good to me.

**Comment by staabm** [comment]
will open a doc PR then, thanks.

**Comment by staabm** [comment]
here we go
https://github.com/jzaefferer/jquery-validation/pull/1530
https://github.com/jzaefferer/validation-content/pull/14

**Pull request closed without merging**
