### PR TITLE
Build: support for commonjs exports

### PR DESCRIPTION
**Pull request by gregorej**
Inspired by [backbone's](https://github.com/jashkenas/backbone/blob/master/backbone.js#L24-L27) commonjs support

### CODE REVIEW

**Comment by Arkni** [comment]
I suggest to do it like this: https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js#L10-L13

**Comment by codeclown** [comment]
Having this merged would be great!

**Comment by staabm** [comment]
@codeclown please adjust it per feedback above

**Comment by codeclown** [comment]
Made a new pull request since not sure how to edit this one or if it's even desired.

https://github.com/jzaefferer/jquery-validation/pull/1621

**Pull request closed without merging**
