### PR TITLE
Additionals: Add dateMultipleFormat validator

### PR DESCRIPTION
**Pull request by Arkni**
With this validator, we can do the following:
* Using the default format `DD/MM/YYYY`
```
dateInput: {
    dateMultipleFormat: true // or {}
}

// Or
dateInput: {
    dateMultipleFormat: {
        minDate: "31/01/2014",  // Or new Date( 2014, 0, 31 )
        maxDate: "31/01/2016"   // Or new Date( 2016, 0, 31 )  
    }
}
```
* Using other date formats with specific separator
```
dateInput: {
    dateMultipeFormat: {
        format: "YYYY-MM-DD",
        separator: "-"
    }
}
```
* Check for minDate and maxDate
```
dateInput: {
    dateMultipeFormat: {
        format: "DD-MM-YYYY",   // Required if format <> "DD/MM/YYYY"
        separator: "-",         // Required if separator <> "/"
        minDate: "01-01-2014",  // Or new Date( 2014, 0, 1 )
        maxDate: "01-01-2016"   // Or new Date( 2016, 0, 1 )
    }
}
```

### CODE REVIEW

**Comment by jzaefferer** [comment]
Thank you for the contribution. This is quite a lot of code, so I won't be able to review fully in the next days.

Maybe @staabm can take a look.

**Comment by Arkni** [comment]
Take your time !

**Comment by Arkni** [comment]
Any update here ?

**Comment by ltdeta** [comment]
@Arkni

using more than one format to test again a date and put it into a defined output format
something like that:
````js
method( "04.12.2003", { format: ["MM.DD.YYYY", "M.D.YYYY", "MM.DD.YY", "M.DD.YY", "M.D.YY"], separator: "." } ), "valid (Format: MM.DD.YYYY)"
````
* 01.01.2014   => should be valid
* 1.1.2014       => should be valid
* 1.01.2014     => should be valid
* 1.1.14           
=> should be valid 
current century 1.1.2014 (or a threshold to put it into last century example  < 50 => 19   >=50 > 20)

**Comment by Arkni** [comment]
@ltdeta 

the following dates:
* 01.01.2014
* 01.01.2014
* 1.1.2014
* 1.01.2014

are all valid if you are using: 
```
{
    format: "DD.MM.YYYY",
    separator: "."
}
```

For other formats, I will try to add support for them when I have some time.

**Comment by ltdeta** [comment]
Thanks, what so you think about a parameter like 'outputFormat' ?

**Comment by Arkni** [comment]
The  ``outputFormat`` parameter mean that after validation success, we have
to change the field value to match it, right ?

**Comment by ltdeta** [comment]
yes

**Comment by ltdeta** [comment]
```dateMultipleFormat ``` should accept empty values as ```valid```
```js
var format      = options.format ? options.format.toUpperCase() : "DD/MM/YYYY",
separator   = options.separator || "/",
dateFormats = format.split( separator ), // Split the format to 3 values YYYY, MM & DD
dateValues  = value.split( separator ),  // Split the date to 3 values year, month & day
year        = dateValues[ dateFormats.indexOf( "YYYY" ) ],
month       = dateValues[ dateFormats.indexOf( "MM" ) ],
day         = dateValues[ dateFormats.indexOf( "DD" ) ],
date, minDate, maxDate, valid;
```
**insert**
```js
// Check if dateValue is empty
if ($jq.trim(value).length==0) {
 return true;
}

**Comment by Arkni** [comment]
@ltdeta 

I think I should add this instead:
```js
// If the field is optional and empty
// exit with success
if ( this.optional( element ) ) {
	return true;
}
```

**Comment by ltdeta** [comment]
You are right

**Comment by Arkni** [comment]
@ltdeta 

>using more than one format to test against a date and put it into a defined output format
something like that:
```js
method( "04.12.2003", 
{ format: ["DD.MM.YYYY", "D.M.YYYY",  "D.MM.YYYY",  "DD.M.YYYY", 
             "DD.MM.YY", "D.MM.YY", "DD.M.YY", "D.M.YY"], 
  separator: "."  , 
  formatOutput:"MM.DD.YYYY"} 
), "valid (Format: MM.DD.YYYY)");
```
01.01.2014 => should be valid => output: 01.01.2014
1.1.2014 => should be valid => output: 01.01.2014
1.01.2014 => should be valid => output: 01.01.2014
1.1.14 => should be valid => output: 01.01.2014 current century 1.1.2014 (or a threshold to put it into last century example < 50 => 19 >=50 > 20)

Check this branch [dateMultipleFormatPatch](https://github.com/Arkni/jquery-validation/tree/dateMultipleFormatPatch) to see the implementation of this feature.

PS: feel free to use it as you want.

**Comment by Arkni** [comment]
@jzaefferer 
Any update on this PR ?

**Comment by jzaefferer** [comment]
Thanks again, but this is still way more code than I'm willing to maintain in this repository. I suggest your create a seperate repo on your own GitHub account and include the tests there, along with a readme and demo.

**Comment by Arkni** [comment]
@jzaefferer 
Already created, see https://github.com/Arkni/date-validator

Thanks

**Comment by jzaefferer** [comment]
:+1:

**Comment by jzaefferer** [comment]
You can still add a demo, maybe use gh-pages to host it.

**Comment by Arkni** [comment]
I will add it as soon as possible.
Thanks

**Pull request closed without merging**
