### PR TITLE
CONTRIBUTING: Added a hint on how to run the testsuite

### PR DESCRIPTION
**Pull request by staabm**
using php

### CODE REVIEW

**Comment by jzaefferer** [comment]
PHP isn't a requirement anymore, since all remote requests are mocked with mockjax. Could you update this to just remove the need for a local server?

**Comment by staabm** [comment]
Using this webserver php local webserver it was very easy for me to run the tests (so no grunt required)

Nevertheless you prefer the way running it using grunt and without a webserver, right?

**Comment by jzaefferer** [comment]
No, I meant that you can just run `test/index.html` from the filesystem in your browser, no webserver nor grunt required.

**Comment by staabm** [comment]
Using the `file:///`protocol?

**Comment by jzaefferer** [comment]
Yep

**Comment by staabm** [comment]
@jzaefferer here we go

**Comment by jzaefferer** [comment]
Thanks!

**Pull request closed without merging**
