### PR TITLE
Localisation: Update Malay translation

### PR DESCRIPTION
**Pull request by od3n**

### CODE REVIEW

**Comment by od3n** [comment]
Fixed conflict file

**Comment by Arkni** [comment]
After fetching your branch locally, here is what I get when using gitk:

screenshot from 2015-10-31 15 34 05

You see the red arrow, it points to your first commit (which you did based on the outdated master), it caused because instead of rebasing your branch on top of `upstream/master`, you did a normal `git pull` or `git merge upstream/master`.

What you have to do (what I advise) before even changing any of the files or committing some changes, is -- if you already [configured a remote that points to the upstream repository](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and named it `upstream` -- following this guide by Github about [Syncing a fork](https://help.github.com/articles/syncing-a-fork/). If you don't want to follow the Github guide, you can read this chapter from `Pro Git`: [Git rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) which is very interesting and helpful.

See also this [Stackoverflow question](http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository).

And then, do your changes and commit :) that way you won't get any conflict, and the history will be clean.

So, please rebase your branch, and then push again (change only the relevant 3 lines)

Thanks :)

**Comment by od3n** [comment]
@Arkni Thanks for the note. PR updated

**Comment by staabm** [comment]
Please prefix the commit message with "Localisation:"

**Comment by staabm** [comment]
@od3n please prefix the commit message, the PR title is not that important :-)

**Comment by Arkni** [comment]
This command will do the trick for you:
```
$ git commit --amend -m "Localisation: $(git log -1 --pretty=%B)"
```

**Comment by od3n** [comment]
Updated, thanks for the guidance.

**Comment by staabm** [comment]
Thx

**Pull request merged**
