### PR TITLE
Translated Additional Methods - pt-BR

### PR DESCRIPTION
**Pull request by jcspader**

### CODE REVIEW

**Comment by staabm** [comment]
@jcspader this needs a rebase

**Comment by jcspader** [comment]
@staabm Hi Markus.
I don't understand. What do you want me to do?

**Comment by staabm** [comment]
The proposed patch doesnt merge cleanly as some other PRs changed some lines in the same area.

Could you checkout the file from the current master-branch and do the changes again? If your git FU is not strong enough, just open annew PR.

Thanks.

**Comment by jcspader** [comment]
@staabm It's done.

**Pull request closed without merging**
