### PR TITLE
Include Minified Version in NPM Package

### PR DESCRIPTION
**Pull request by RehanSaeed**
Solves https://github.com/jzaefferer/jquery-validation/issues/1772

### CODE REVIEW

**Comment by staabm** [comment]
merged, thx.

**Comment by mi2oon** [comment]
@staabm  I can't seem to find it anywhere. Where is it merged to?

**Comment by Arkni** [comment]
@mi2oon merged to master. See 2aa891595555c02302fdfe7a1715862abf72c18d

The build will be done in the release process of the next version.

**Comment by mi2oon** [comment]
@Arkni There it was, thanks. Can't wait 😄

**Pull request closed without merging**
