### PR TITLE
Fixing additional/cifES and additional/nieES algorithms

### PR DESCRIPTION
**Pull request by alfonsomartinde**
### Description

This PR will improve additional/cifES and additional/nieES algorithms regarding on some comments found at http://moreovercoder.blogspot.com.es/2013/07/validacion-de-nie-nif-y-cif-con-jquery.html

Will fix:
https://github.com/alfonsomartinde/jquery-validation/issues/1

Thank you!

### CODE REVIEW

**Comment by staabm** [comment]
looks really good to me. could you rebase and squash all the commits into one?

**Comment by alfonsomartinde** [comment]
Yep, sure! I'm not quite familiarised with rebasing, sorry about that, but I'll figure out how to do it. Any help will that be very welcome :)

**Comment by staabm** [comment]
see e.g. https://help.github.com/articles/using-git-rebase/

**Comment by alfonsomartinde** [comment]
Not sure if I did it properly...

**Comment by staabm** [comment]
merged. great job, thx.

**Pull request merged**
