### PR TITLE
Additional: Fixed validation for specific case for Spanish NIFs.

### LINKED ISSUE #1913: Additional : Bug in nifES validation method for Temporary foreign NIFs.
Temporary foreign nifs are not well validated by the nifES method. Format example M1503708Z should be valid but its failing the validation.

### PR DESCRIPTION
**Pull request by jarey**
Fixed bug in validation of Spanish nif for specific case of temporary foreign NIFs.
Added test for specific case.

Closes #1913

Thank you!

### CODE REVIEW

**Comment by alfonsomartinde** [comment]
Thank you @jarey, your code fixes the issue. Well done! 👍

**Comment by franrc89** [comment]
Very useful. Thank you @jarey

**Comment by staabm** [comment]
Build restarted... lets see

**Comment by staabm** [comment]
Awesome, was a build issue. Thx for the PR.

**Pull request merged**
