### PR TITLE
added doc reference to jQuery.validator.methods

### PR DESCRIPTION
**Pull request by staabm**
see https://github.com/jzaefferer/validation-content/pull/14

### CODE REVIEW

**Comment by staabm** [comment]
maybe we should even link to the new doc page in README and CONRTIBUTE files?

**Comment by jzaefferer** [comment]
Yes, let's mention in wherever we mention email validation.

**Comment by staabm** [comment]
@jzaefferer any news?

**Comment by staabm** [comment]
I try to publish the docs on my own this week.

**Pull request closed without merging**
