### PR TITLE
Build: Adds CommonJS-support in build process. Enhances PR #1597

### PR DESCRIPTION
**Pull request by codeclown**
See https://github.com/jzaefferer/jquery-validation/pull/1597

### CODE REVIEW

**Comment by staabm** [comment]
@codeclown did you test this change? I am asking because I am not at a workstation right now and we dont have test coverage for this kind of things

**Comment by codeclown** [comment]
Yes, tested locally. Unfortunately the dist-version is not included in the repo because it requires integration, but I have included it [here](https://gist.github.com/codeclown/45aeaf3f10f714c274e9) so anyone can test requiring it as well.

**Comment by staabm** [comment]
@Arkni any outstanding issues?

**Comment by Arkni** [comment]
LGTM :)

**Pull request merged**
