### PR TITLE
Fix group validation

### PR DESCRIPTION
**Pull request by TLib**

### CODE REVIEW

**Comment by staabm** [comment]
What does this PR fix? In which scenario this fix is required.

This fix is a BC break.

**Comment by Arkni** [comment]
#1816 describes this issue very well, also it provides a jsfiddle.

**Comment by staabm** [comment]
Would be great to have a unit test then.

**Comment by Arkni** [comment]
@TLib 
You can add this test which should fail without your fix:
```diff
 test/index.html | 19 +++++++++++++++++++
 test/test.js    | 33 +++++++++++++++++++++++++++++++++
 2 files changed, 52 insertions(+)

diff --git a/test/index.html b/test/index.html
index 9ddda8e..cfda6d9 100644
--- a/test/index.html
+++ b/test/index.html
@@ -414,6 +414,25 @@
 	<form id="testForm25">
 		<input type="text" data-rule-required="true" title="something25" name="something25" id="something25" value="">
 	</form>
+	<form id="testForm26">
+		<select name="day" class="required">
+			<option value="">day</option>
+			<option value="1">1</option>
+			<option value="2">2</option>
+		</select>
+		<br>
+		<select name="month" class="required">
+			<option value="">month</option>
+			<option value="1">1</option>
+			<option value="2">2</option>
+		</select>
+		<br>
+		<select name="year" class="required">
+			<option value="">year</option>
+			<option value="2015">2015</option>
+			<option value="2016">2016</option>
+		</select>
+	</form>
 </div>
 </body>
 </html>
diff --git a/test/test.js b/test/test.js
index 17f3b5a..821579a 100644
--- a/test/test.js
+++ b/test/test.js
@@ -1088,6 +1088,39 @@ test( "validating groups settings parameter", function() {
 	equal( validate.groups[ "input-six" ], "stringGroup" );
 } );

+QUnit.test( "validating group of elements", function( assert ) {
+	var form  = $( "#testForm26" ),
+		day   = form.find( "[name='day']" ),
+		month = form.find( "[name='month']" ),
+		year  = form.find( "[name='year']" ),
+		event = $.Event( "keyup", { keyCode: 9 } ),
+		v = form.validate( {
+			groups: {
+				mydate: "day month year"
+			}
+		} ),
+		invalidEls;
+
+	v.form();
+
+	assert.equal( v.invalidElements().length, 3, "All 3 elements are invalid" );
+
+	// Tab to `month`
+	day.blur();
+	month.trigger( event );
+	month.focus();
+
+	month.val( 2 );
+
+	// Trigger validation via click event
+	month.trigger( "click" );
+
+	invalidEls = v.invalidElements();
+
+	assert.equal( invalidEls.length, 2, "Only 2 elements are invalid" );
+	assert.deepEqual( invalidEls[ 0 ], day[ 0 ], "The day element is invalid" );
+	assert.deepEqual( invalidEls[ 1 ], year[ 0 ], "The year element is invalid" );
+} );
+
 test( "bypassing validation on form submission", function() {
 	var form = $( "#bypassValidation" ),
 		normalSubmission = $( "form#bypassValidation :input[id=normalSubmit]" ),
```

**Comment by staabm** [comment]
patch landed via 623baabd3e3875f921654ed7614c8cae79ebf203

tests landed via 45c4b17f451a7b589a74dd74d4e2e3dd12a91fd2

thank you guys!

**Comment by staabm** [comment]
@Arkni btw. I wasnt able to apply your diff using the `patch` command.. (Did it manually then) Whats the steps to apply such a diff? Could you elaborate?

**Comment by Arkni** [comment]
The diffs I often generate are created using `git diff --patch-with-stat` (no authorship and commit infos included).

To apply those changes to your working tree, you can put the diff into a file (e.g. `PRXX.diff`) and then (don't forget to commit the changes) use the command `git apply` [1]:
```
git apply /path/to/PRXX.diff
```

In case I want to preserve the authorship of my patch, I will then create a patch using the command `git format-patch` [2],  because it will transfers the authorship info and the commit message (author, date, commit msg ...):
```bahs
# I often do the change in a new branch
git format-patch master --stdout > my_patch.patch
```
and then either I upload that file or just put its content in a commit.
To apply the patch, you have to use the command `git am` [3]:
```
git am my_patch.patch
```
Now, all commits from the patch file were applied to your master branch.

This [article](https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/) will help you get-started quickly. You might also be interested in checking this [chapter form `Pro Git`](https://git-scm.com/book/en/v2/Distributed-Git-Maintaining-a-Project#Applying-Patches-from-Email) book which has more information.

----
[1] https://git-scm.com/docs/git-apply
[2] https://git-scm.com/docs/git-format-patch
[3] https://git-scm.com/docs/git-am

**Pull request closed without merging**
