### PR TITLE
Core: Split out `creditcard` method

### PR DESCRIPTION
**Pull request by Arkni**
As mentioned by Jörn in [#1506 (comment)](https://github.com/jzaefferer/jquery-validation/issues/1506#issuecomment-116327217)

### CODE REVIEW

**Comment by staabm** [comment]
In case we have unit tests for this method, please move them into `test/additional/creditcard.js`.

In case we dont have any, would be great you could add simple coverage

**Comment by Arkni** [comment]
> In case we have unit tests for this method, please move them into test/additional/creditcard.js.

Yes, there is a unit test for this method and it's under `methods` modules in `test/methods.js`
There is also a module named `additional methods` [(test/methods.js#L520)](https://github.com/jzaefferer/jquery-validation/blob/master/test/methods.js#L520) in the same file that contains the test for other additional methods.

I think I have to move all test for additional method to be under `additional methods` module. Or do I have to create a new file named `additional-methods.js` that will contains all test for the availabale additional methods ?

**Comment by staabm** [comment]
I would expect to have one test file for each source file. Each testfile should contain only tests which cover the code in the corresponding src file. I guess this should be the long/mid-term goal. 

Please dont touch tests other then those related to creditcard within this PR though.

**Comment by Arkni** [comment]
> I would expect to have one test file for each source file. Each testfile should contain only tests which cover the code in the corresponding src file. I guess this should be the long/mid-term goal.

Sounds good to me, but this will required assembling all testfiles into one named `additional-methods.js` or just append them to `methods.js`. So it will be easy to include them in `test.html`

Your thoughts ?

**Comment by staabm** [comment]
@Arkni I am fine with anlong list of includs, dont need a file just for the purpose to add a unnecessary indirection

**Comment by staabm** [comment]
I mean we only need to list them here, right?
https://github.com/jzaefferer/jquery-validation/blob/master/test/index.html#L14

**Comment by Arkni** [comment]
> @Arkni I am fine with a long list of includes.. dont need a file just for the purpose to add a unnecessary indirection, because performance is not a primary concern in tests

make sense.

> I mean we only need to list them here, right?
> https://github.com/jzaefferer/jquery-validation/blob/master/test/index.html#L14

I will do that for `creditcard` method and in another PR for other additional methods

**Comment by staabm** [comment]
> and in another PR for other additional methods
Yes we can do this in the same stroke when moving code of additionals away from core.js

**Comment by Arkni** [comment]
There is a problem.

All method tests are depend on a method named [`methodTest`](https://github.com/jzaefferer/jquery-validation/blob/master/test/methods.js#L3-L12), which is defined inside a closure in `methods.js`.

I don't want to replicate the code.
Your thoughts please ?

**Comment by staabm** [comment]
We only need to include our new test files after the method.js in the index.html

**Comment by Arkni** [comment]
> I guess we need to move the methodTest into the global scope for now, so outside the closure.

Or event better by removing [methods.js#L1](https://github.com/jzaefferer/jquery-validation/blob/master/test/methods.js#L1)  and the last one [methods.js#L1276](https://github.com/jzaefferer/jquery-validation/blob/master/test/methods.js#L1276).

**Comment by staabm** [comment]
Not sure why we have this closure their in the first place. I am ok with dropping it in case test suite stays green

**Comment by Arkni** [comment]
> Not sure why we have this closure their in the first place. I am ok with dropping it in case test suite stays green

Done and test suite is green :white_check_mark:

**Comment by staabm** [comment]
Looks perfect, thx. Will land this PR after we got some docs for it.

**Comment by staabm** [comment]
Tanks man. :fireworks:

**Comment by Arkni** [comment]
My pleasure :)

**Comment by nebrot** [comment]
The creditcard-method is now in the wrong list [docs](http://jqueryvalidation.org/documentation/#link-list-of-built-in-validation-methods), should be listed below in additional-methods-list.

**Comment by Arkni** [comment]
@nebrot 
Good catch, thanks for pointing out :)

**Pull request merged**
