### PR TITLE
No need for spaces inside brackets

### PR DESCRIPTION
**Pull request by hugovk**
In English, it looks a bit odd with spaces inside brackets.

### CODE REVIEW

**Comment by Arkni** [comment]
Would you mind editing this line too: https://github.com/jzaefferer/jquery-validation/blob/3de30ac8a173c844fab128ef0ebdef59a6b4e964/src/localization/messages_ge.js#L12

**Comment by hugovk** [comment]
@Arkni Done!

**Comment by staabm** [comment]
thx for the PR. did you check all localization files for this "problem"?

**Comment by hugovk** [comment]
Those are the only two like that.

**Comment by staabm** [comment]
thx

**Pull request closed without merging**
