### PR TITLE
add predict for remote validation response

### PR DESCRIPTION
**Pull request by zdjray**
Sometimes we need to custom the remote validation json in response.
Here we add predict for this situation.

### CODE REVIEW

**Comment by staabm** [comment]
whats your use case? what is this code supposed to do?

**Comment by zdjray** [comment]
the situation is:
the remote REST API has its own response format,just like this:
```javascript
{
    result: 0,
    msg: 'OK'
}
```
or this:
```javascript
{
    result: -1,
    msg: 'some error occurs'
}
```
when result is 0,it means the validation is correct.

**Comment by staabm** [comment]
wouldn't jquerys `dataType` or `dataFilter` option of `jQuery.ajax`[1] do the job for you?

[1] http://api.jquery.com/jQuery.ajax/

**Comment by zdjray** [comment]
thanks for the perfect solution,that will work for me
it's a great idea:D

**Pull request closed without merging**
