### PR TITLE
Fix regressions introduced in #1644 and #1657

### PR DESCRIPTION
**Pull request by Arkni**
//Cc @Maks3w

### CODE REVIEW

**Comment by Maks3w** [comment]
Good for me.

Just one more thing. @staabm Please add this deprecations to release notes

**Comment by staabm** [comment]
@Arkni can we get a unit test into this PR?

**Comment by Arkni** [comment]
Sure!
I'll add them as soon as possible.

**Comment by Arkni** [comment]
@staabm 
Added the tests!

**Comment by staabm** [comment]
merged, thx!

**Comment by Arkni** [comment]
@staabm 

we forgot this:
> Just one more thing. @staabm Please add this deprecations to release notes

Can you add it please ?

**Pull request closed without merging**
