### PR TITLE
fix: do not find wrapper for contains when call hideThese()

### PR DESCRIPTION
**Pull request by zhenyong**
https://jsfiddle.net/feipigzi/62k3998L/

### CODE REVIEW

**Comment by staabm** [comment]
What the issue you are trying to fix? Could you provide a jsfiddle showing the error scenario?

**Comment by zhenyong** [comment]
@staabm https://jsfiddle.net/feipigzi/62k3998L/

**Comment by staabm** [comment]
Could you elaborate a bit further. I am not sure this is a bug right now.

**Comment by staabm** [comment]
closing, because no feedback. feel free to discuss your issue further.

**Pull request closed without merging**
