### PR TITLE
Aditional: case-insensitive check for BIC

### PR DESCRIPTION
**Pull request by Arkni**
Squashed and rebased #1547.
The authorship still maintained. So you can close #1547 in favor of this one

### CODE REVIEW

**Comment by staabm** [comment]
@Arkni would you mind adding a unit test?

**Comment by Arkni** [comment]
will do when time allows.

**Comment by Arkni** [comment]
@staabm 
Done!

**Comment by staabm** [comment]
thx. next step for me is learning "how to merge it right" ;)

**Comment by Arkni** [comment]
> next step for me is learning "how to merge it right" ;)

Yep :grin:

**Comment by staabm** [comment]
merged as 3f3fb8c2ed4652227cee3dab00c2a1775284d565 c5ccf06dd7ef638914be35b65394e5f07e8b961f

**Comment by Arkni** [comment]
> Achievement unlocked :-)

Good :D

> next time I will try to let the commit message autoclose the PR :-).

Yes, it helps avoiding closing issues and PR manually.

**Pull request closed without merging**
