### PR TITLE
Feature: Make remote complete function more useful

### PR DESCRIPTION
**Pull request by rain01**
Added an option to remote rule to send more data from server than just valid status and error message.

This feature is backwards compatible, meaning everything will still work without changing your code but now you could make it more advanced if your server response is this...

Server json response:
```javascript
{
    valid: true,
    whatever: 'my random data'
}
```

Feature request #1491

### CODE REVIEW

**Comment by staabm** [comment]
This doesn't look like the way to go. We should not dictate the strutcture of the JSON required.

Maybe we should add a callback instead which can decide - using `return true/false` - whether the returned response was "valid"?

**Comment by jzaefferer** [comment]
I agree that this format is too specific. A callback would be more flexible. There's also the relate PR #1353. I don't have an answer yet.

**Comment by rain01** [comment]
@staabm JSON is not required but optional... you can still return true\false or str but when you return JSON you can add more data to it.

Adding a callback would be a different feature, probably wouldn't satisfy #1491 and it would be much more complicated.

**Comment by staabm** [comment]
> Adding a callback would be a different feature, probably wouldn't satisfy #1491 and it would be much more complicated.

why wouldn't this satisfiy the ticket?
you would have a callback for the response (implemented in your app, instead of the lib) which checks the JSON response and returns `true/false` whenever the JSON contains a `valid: true/false` property ?

**Comment by rain01** [comment]
> your logic atm dictates how the json is interpreted.

That's how JSON is... have to interpret it some way... no?

> One issue with your approach is e.g. when someone returns a object with a property named valid the interpretation would be completly different, after your change would land in the library. 

Right now if you return an object, it would do nothing doesn't matter if there is 'valid' or not in there... that's why I added the new feature where you could return an object.

> Additionally this renders to be a BC break.

How would it be BC break? You can still do everything you do now returning bool or str and it would work the same way... only when you return JSON you have new options as oppose to not doing anything.

>why wouldn't this satisfiy the ticket?
you would have a callback for the response (implemented in your app, instead of the lib) which checks the JSON response and returns true/false whenever the JSON contains a valid: true/false property?

Maybe I don't understand how you would do that but isn't remote's "complete" already a callback? Where would you put that callback in #1491 situation?

If the callback is the answer then can someone do it or show how it's done?

**Comment by jzaefferer** [comment]
This isn't a good enough solution. I've also commented on the underlying issue.

**Pull request closed without merging**
